apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service-deployment
  namespace: ndhai-greeting
  labels:
    app: greeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: greeting-service
          image: greeting-service:0.0.1
          ports:
            - containerPort: 8080
            - containerPort: 6565
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/readiness
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          env:
            - name: SERVER_HTTP_PORT
              value: "8080"
            - name: SERVER_GRPC_PORT
              value: "6565"
            - name: ZIPKIN_BASE_URL
              value: "http://tempo-service.monitoring:9411"

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: ndhai-greeting
  labels:
    svc: greeting-service
spec:
  clusterIP: None
  selector:
    app: greeting-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 6565
      targetPort: 6565


