apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate-service-deployment
  namespace: ndhai-aggregate
  labels:
    app: aggregate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregate-service
  template:
    metadata:
      labels:
        app: aggregate-service
    spec:
      containers:
        - name: aggregate-service
          image: aggregate-service:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          env:
            - name: SERVER_HTTP_PORT
              value: "8080"
            - name: ZIPKIN_BASE_URL
              value: "http://localhost:9411"
            - name: GREETING_HOST
              value: "greeting-service.ndhai-greeting"
            - name: GREETING_PORT
              value: "6565"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
  namespace: ndhai-aggregate
  labels:
    app: aggregate-service
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: aggregate-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aggregate-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: aggregate-service-ingress
  rules:
    - http:
        paths:
          - path: /aggregate
            pathType: Prefix
            backend:
              service:
                name: aggregate-service
                port:
                  number: 8080