apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate-service-deployment
  namespace: ndhai-aggregate
  labels:
    app: aggregate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregate-service
  template:
    metadata:
      labels:
        app: aggregate-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: aggregate-service
          image: aggregate-service:0.0.2
          ports:
            - containerPort: 8080
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/readiness
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          env:
            - name: SERVER_HTTP_PORT
              value: "8080"
            - name: ZIPKIN_BASE_URL
              value: "http://tempo-service.monitoring:9411"
            - name: GREETING_HOST
              value: "greeting-service.ndhai-greeting"
            - name: GREETING_PORT
              value: "6565"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregate-service
  namespace: ndhai-aggregate
  labels:
    svc: aggregate-service
spec:
  clusterIP: None
  selector:
    app: aggregate-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

