server:
  port: ${SERVER_HTTP_PORT:8080}
spring:
  application:
    name: aggregate-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

greeting:
  host: ${GREETING_HOST:localhost}
  port: ${GREETING_PORT:6565}
  ssl: false
  max-retries: 3
  timeout: 2s
  keep-alive: 10m
