server:
  port: ${SERVER_HTTP_PORT:8081}
  http2:
    enabled: true
grpc:
  enabled: true
  port: ${SERVER_GRPC_PORT:6565}
  enableReflection: true

spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: true
        step: 1m
        url: ${OTLP_METRICS_URL:http://localhost:4318/v1/metrics}
    tracing:
      endpoint: ${OTLP_TRACE_URL:http://localhost:4318/v1/traces}